---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-05T08:18:22Z"
  labels:
    app: some-postgis-pod
  name: some-postgis-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_DB
      value: metlink
    image: docker.io/postgis/postgis:16-3.4-alpine
    name: some-postgis
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgsql-pvc
  volumes:
  - name: pgsql-pvc
    persistentVolumeClaim:
      claimName: pgsql